#!/usr/bin/perl -w

use XML::XPathScript;

use Symbol;
use File::Basename;

if (@ARGV == 1) { @ARGV=($ARGV[0].".xml", $ARGV[0].".xps"); }
usage() unless @ARGV == 2;

my ($xmlfile, $stylefile) = @ARGV;

my $xml = gensym;

open($xml, $xmlfile) || die "Cannot open XML file '$xmlfile': $!";

my $xps = XML::XPathScript->new(xml => $xml, stylesheetfile => $stylefile);

$xps->process;

exit(0);

sub usage {
    print STDERR <<EOT;
Usage: xpathscript xmlfile stylesheetfile
EOT
    exit(0);
}
