#!/usr/bin/perl -w

use XML::XPathScript;

use Symbol;
use File::Basename;

usage() unless @ARGV == 2;

my ($xmlfile, $stylefile) = @ARGV;

my $xml = gensym;
my $stylesheet = gensym;

open($xml, $xmlfile) || die "Cannot open XML file '$xmlfile': $!";
chdir dirname($stylefile);
open($stylesheet, basename($stylefile)) || die "Cannot open Stylesheet file '$stylefile': $!";

my $xps = XML::XPathScript->new(xml => $xml, stylesheet => $stylesheet);

$xps->process;

exit(0);

sub usage {
    print STDERR <<EOT;
Usage: xpathscript xmlfile stylesheet_file
EOT
    exit(0);
}
